/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EarThereumInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getExistingSampleIDs"
      | "getSampleData"
      | "getSampleDatas"
      | "samples"
      | "uploadSample"
      | "uploadSamples"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getExistingSampleIDs",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSampleData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSampleDatas",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "samples", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "uploadSample",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadSamples",
    values: [BytesLike[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExistingSampleIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSampleData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSampleDatas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "samples", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploadSample",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadSamples",
    data: BytesLike
  ): Result;
}

export interface EarThereum extends BaseContract {
  connect(runner?: ContractRunner | null): BaseContract;
  attach(addressOrName: AddressLike): this;
  deployed(): Promise<this>;

  interface: EarThereumInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getExistingSampleIDs: TypedContractMethod<
    [ids: BytesLike[]],
    [[string[], bigint] & { existingSampleIDs: string[]; smpCount: bigint }],
    "view"
  >;

  getSampleData: TypedContractMethod<[id: BytesLike], [string], "view">;

  getSampleDatas: TypedContractMethod<[ids: BytesLike[]], [string[]], "view">;

  samples: TypedContractMethod<
    [arg0: BytesLike],
    [[string, bigint] & { data: string; header: bigint }],
    "view"
  >;

  uploadSample: TypedContractMethod<
    [id: BytesLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  uploadSamples: TypedContractMethod<
    [ids: BytesLike[], sampleData: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getExistingSampleIDs"
  ): TypedContractMethod<
    [ids: BytesLike[]],
    [[string[], bigint] & { existingSampleIDs: string[]; smpCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSampleData"
  ): TypedContractMethod<[id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSampleDatas"
  ): TypedContractMethod<[ids: BytesLike[]], [string[]], "view">;
  getFunction(
    nameOrSignature: "samples"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, bigint] & { data: string; header: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "uploadSample"
  ): TypedContractMethod<
    [id: BytesLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "uploadSamples"
  ): TypedContractMethod<
    [ids: BytesLike[], sampleData: BytesLike[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
